version: '3.5'

services:
  ffanime:
    image: binarii/ffanime
    container_name: ffanime
    restart: always
    shm_size: 1g
    ports:
      - "8686:8686"
    volumes:
      - /data/ffanime:/data/ffanime
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8686/health || exit 1"]
    # environment:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         device_ids: ['0', '1']
    #         capabilities: [gpu]
